### ISSUE TITLE
MacIPTV Extension - Unable to Add Mac Address

### ISSUE THREAD

**Issue by indiarocks08** [MustardChef/eddyarchive#2]
Hi, Is there any option to manage MacIPTV Extension and add Portal Url along with extension without needing to change in this . KT file everytime and build project?

As I have see you have given option for Tags account, Can you also provide option for MAC address with url

**Comment by MustardChef** [comment]
> KT

@EL-R1 Unforunately, I am not the developer of this repo. This repo is a backup that I created of the original repo (https://github.com/Eddy976/cloudstream-extensions-eddy) which was taken down because of DMCA. You can join the Discord and request sites to be added and report issues.
